This is the python code for the feeding system. It is set to operate the servo motor at regular intervals to particlular angle....
So the tank is fed at regular intervals by opening and closing he lid using the servo motor
